### ISSUE TITLE
Inserir bonde-migrations no workflow de desenvolvimento do Bonde

### ISSUE THREAD

**Issue by igr-santos** [nossas/bonde-migrations#2]
* A primeira migração deste repositório deve possuir a configuração atual da base de dados do Bonde em produção, todas as tabelas e relacionamentos pertencentes a estrutura do Bonde e suas dependencias.

* Esse serviço deve substituir dentro do processo de migração no CI e no desenvolvimento (https://github.com/nossas/bonde-install) o atual serviço feito em RubyOnRails (https://github.com/nossas/bonde-server).

**Comment by lpirola** [comment]
@igr-santos resolvido em https://github.com/nossas/bonde-migrations/pull/11
